export const cities = [
  'AMSTERDAM',
  'ATHINAI (Athens)',
  'BEOGRAD (Belgrade)',
  'BERLIN',
  'BUCURESTI (Bucharest)',
  'BUDAPEST',
  'Barcelona',
  'Barnaul',
  'Birmingham',
  'Bremen',
  'Chelyabinsk',
  'Dnepropetrovsk',
  'Donetsk',
  'Dortmund',
  'Duisburg',
  'Düsseldorf',
  'Ekaterinoburg',
  'Essen',
  'Frankfurt am Main',
  'Genova',
  'Glasgow',
  'HELSINKI',
  'Hamburg',
  'Hannover',
  'Irkutsk',
  'Izhevsk',
  'KIEV',
  'KISHINEV',
  'KOBENHAVN (Copenhagen)',
  'Kazan',
  'Kemerovo',
  'Khabarovsk',
  'Kharkov',
  'Kraków',
  'Krasnodar',
  'Krasnoyarsk',
  'Kryvy Rig',
  'Köln (Cologne)',
  'LISBOA (Lisbon)',
  'LONDON',
  'Leeds',
  'Lipetsk',
  'Lvov',
  'Lódz',
  'MADRID',
  'MINSK',
  'MOSKVA (Moscow)',
  'Marseille',
  'Milano (Milan)',
  'Mykolaiv',
  'Málaga',
  'München (Munich)',
  'Naberezhnye Tchelny',
  'Napoli (Naples)',
  'Nizhny Novgorod',
  'Novokuznetsk',
  'Novosibirsk',
  'OSLO',
  'Odessa',
  'Omsk',
  'Orenburg',
  'PARIS',
  'PRAHA (Prague)',
  'Palermo',
  'Penza',
  'Perm',
  'Poznan',
  'RIGA',
  'ROMA',
  'Rostov-na-Donu',
  'Rotterdam',
  'Ryazan',
  'SARAJEVO',
  'SOFIA',
  'STOCKHOLM',
  'Salonika',
  'Samara',
  'Saratov',
  'Sevilla',
  'Sheffield',
  'St Petersburg',
  'Stuttgart',
  'Tolyatti',
  'Torino (Turin)',
  'Tula',
  'Tyumen',
  'Ufa',
  'Ulyanovsk',
  'VILNIUS',
  'Valencia',
  'Vladivostok',
  'Volgograd',
  'Voronezh',
  'WARSZAWA (Warsaw)',
  'WIEN (Vienna)',
  'Wroclaw (Breslau)',
  'Yaroslave',
  'ZAGREB',
  'Zaporozhye',
  'Zaragoza',
];

export const countries = [
  'Austria',
  'Belarus',
  'Bosnia',
  'Bulgaria',
  'Croatia',
  'Czech Republic',
  'Denmark',
  'Finland',
  'France',
  'Germany',
  'Greece',
  'Hungary',
  'Italy',
  'Latvia',
  'Lithuania',
  'Moldova',
  'Netherlands',
  'Norway',
  'Poland',
  'Portugal',
  'Romania',
  'Russia',
  'Serbia',
  'Spain',
  'Sweden',
  'UK',
  'Ukraine',
];
